branches:
  only:
    - source
language: node_js
node_js:
  - "0.10"
script:
  - "hexo generate"
after_success:
  - "git config --global push.default simple"
  - "git clone https://qianlifeng:$PWD@github.com/qianlifeng/qianlifeng.github.io.git git_deploy"
  - "cp -r public git_deploy"
  - "cd git_deploy"
  - "git push"
env:
  global:
    secure: UzQgsicW/ICO8axIS5wAfGnWNbTzMeHpXh+ac4nD3rZbRhH2TeZxbbwDwwMfep0SWrt6U5f+pe2S8v+MIOb+UIp4a4aUZM7QeGj8zHz4juS3GONHrs2oSf09PEamhuA2OKujGu1SRsVJmeRoBx7m9mCRx/bmM2fwXPPbh+swGJc=
