branches:
  only:
    - source
language: node_js
node_js:
  - "0.10"
script:
  - "hexo generate"
after_success:
  - "hexo deploy"
  - "chmod 600 .travis/deploy_key.pem"
  - "ssh-add .travis/deploy_key.pem"
  - "git remote add deploy $REPO"
  - "git push deploy"
