branches:
  only:
    - source
language: node_js
node_js:
  - "0.10"
script:
  - "hexo generate"
after_success:
  - "git config --global push.default simple"
  - "git clone $REPO git_deploy"
  - "cp -r publish git_deploy"
  - "cd git_deploy"
  - "git push"
env:
  global:
    secure: lUMj3nQDaKePP0T376kn6ZvoOM5X6EGihBPi2V1dKDffTVj4Oa5lrKNKQT2BhoioxPcCfJxic74+Y2Or+7J0SwahlWtBDWbGw67TNcbw+PDAAq/7STxbbzJosMKQ2Vgn1jy9SOebbrRZKcEVPV4CHxyxWu3Wbeu5j0q4paqSvE8=
