branches:
  only:
    - source
language: node_js
node_js:
  - "0.10"
script:
  - "hexo generate"
after_success:
  - "git config --global push.default simple"
  - "git clone https://qianlifeng:$PWD@github.com/qianlifeng/qianlifeng.github.io.git git_deploy"
  - "cp -r publish git_deploy"
  - "cd git_deploy"
  - "git push"
env:
  global:
    secure: EORKzoK8q9bDx7R9oxUnJeXPYmopPvh5OJig1+JuCFMNOyRCBeh5wY4lnEegq3C3uLiUmR/o5w0oEIJ1NvijBwhzyd2d5eJVpT4yP/KOX+eY7laLnr1rJaKmFUFPhK8qEOldK5l4j5XjLyUzEhiFkmhROGJSoS+LgywRxekgOmo=
