branches:
  only:
    - source
language: node_js
node_js:
  - "0.10"
script:
  - "hexo generate"
after_success:
  - "git config --global push.default simple"
  - "git remote rm origin"
  - "git remote add origin $REPO"
  - "ls -l"
  - "git push"
env:
  global:
    secure: NZFi1MbGx0uHlaCbk5lD03JdgQjuJQXIKqAlsgz1YXdGa4Jw30GlW1gFGqar8CVftFvAYZl0WOTPbHiIi34TB1/RDknuKm4eTYO+ZJ/mRSYcdxpPMhT26y35ygwTggRu+1SsPByQOpF2uz5SMzMef+BdHomSbUV4h9JkCpCvyJY=
