# Header
menu:
  首页: /
  Github: http://www.github.com/qianlifeng
  博客园: http://www.cnblogs.com/qianlifeng

# Content
excerpt_link: 继续阅读
fancybox: true

# Sidebar
sidebar: right
widgets:
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: scottqian2012
google_plus:
fb_admins:
fb_app_id:
disqus_shortname: maomaoiscoder
