menu:
  首页: /
  极客链接: http://www.geekslink.com

widgets:
- search
- intro 
- category
- tagcloud 

excerpt_link: 阅读全文

twitter:
  username: scottqian2012
  show_replies: false
  tweet_count: 5

addthis:
  enable: true 
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-45522496-1
rss:

comment_provider: 
